### ISSUE TITLE
Don't switch environment to sftp mode after push

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/circleci-orb#28]
See https://discuss.pantheon.io/t/feedback-and-testing-wanted-a-pantheon-circleci-orb/350/14

**Comment by Farnoosh63** [comment]
The link above does not exist or is private. I added `terminus connection:set "$TERMINUS_SITE.$TERMINUS_ENV" git` to post steps. Watching this issue for any updates on this request..

**Comment by maskedjellybean** [comment]
Hi @Farnoosh63 , would you mind giving me and example of adding that line to post steps? Thanks!

**Comment by maskedjellybean** [comment]
Here's what I have in `.circleci/config.yml`, but CircleCI sees the syntax as incorrect and the build fails:

```
version: 2.1
workflows:
  version: 2
  pantheon_push:
    jobs:
      - pantheon/push:
        post-steps:
          - run: terminus connection:set "$TERMINUS_SITE.$TERMINUS_ENV" git

orbs:
  pantheon: pantheon-systems/pantheon@0.2.0
```

The build fails with this error:

```
# ERROR IN CONFIG FILE:
# [#/workflows/pantheon_push] only 1 subschema matches out of 2
# 1. [#/workflows/pantheon_push/jobs/0] 0 subschemas matched instead of one
# |   1. [#/workflows/pantheon_push/jobs/0] expected type: String, found: Mapping
# |   |   SCHEMA:
# |   |     type: string
# |   |   INPUT:
# |   |     push: null
# |   |     post-steps:
# |   |     - run: terminus connection:set \"$TERMINUS_SITE.$TERMINUS_ENV\" git
# |   2. [#/workflows/pantheon_push/jobs/0/post-steps] expected type: Mapping, found: Sequence
# |   |   SCHEMA:
# |   |     type: object
# |   |   INPUT:
# |   |     - run: terminus connection:set \"$TERMINUS_SITE.$TERMINUS_ENV\" git
```

**Comment by stevector** [comment]
Hi @maskedjellybean, I think you need to indent `post-steps`

**Comment by maskedjellybean** [comment]
Thanks @stevector , that was it! My `config.yml` now looks like this:

```
version: 2.1
workflows:
  version: 2
  pantheon_push:
    jobs:
      - pantheon/push:
          post-steps:
            - run:
                name: Reset Development Mode
                command: terminus connection:set ${TERMINUS_SITE}.${TERMINUS_ENV} git

orbs:
  pantheon: pantheon-systems/pantheon@0.2.0
```
