### ISSUE TITLE
Passing parameter to push job

### ISSUE THREAD

**Issue by balcantara90** [pantheon-systems/circleci-orb#48]
I'm passing a false clone_content parameter however in circleci I'm getting this error. Not sure what I'm doing wrong

![image](https://user-images.githubusercontent.com/2055259/88769159-6a43ac00-d1bf-11ea-9ed9-82ac31710204.png)

```
  compile_sass_and_push:
    jobs:
      - npmbuild_and_persist
      - pantheon/push:
          clone_content: false
          requires:
            - npmbuild_and_persist
          checkout: false
          pre-steps:
            - checkout
            - run: composer install --no-dev --optimize-autoloader
```
